server:
  port: 9527
github:
      client:
             id: "Iv1.f0ce44baaa88996e"
             secret: "90fcb9a472305727d41953e99e8a2897b466b9a5"
      Redirect:
              url: "http://localhost:9527/callback"
spring:
       datasource:
         type: com.alibaba.druid.pool.DruidDataSource
         driver-class-name: com.mysql.jdbc.Driver
         url: "jdbc:mysql:///vue?characterEncoding=UTF-8"
         username: root
         password: root
       rabbitmq:
         username: guest
         password: guest
         host: 10.10.32.85
         port: 5672
         #开启confirms回调
         publisher-confirms: true
         #开启 returnedMessage回调
         publisher-returns: true
mybatis:
  mapper-locations: classpath:com/www/community/dao/mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
## 线上需要关闭，配置为true是为了在本地环境执行生成swagger文档
swagger:
  enable: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  PageRowBounds: true